// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_G8q7MsBTAdA0TISIdvFQTfVOi5HjRk',
    appId: '1:474736990075:web:b6d092047cc8c8e0758fde',
    messagingSenderId: '474736990075',
    projectId: 'yaadsaathi-2007',
    authDomain: 'yaadsaathi-2007.firebaseapp.com',
    storageBucket: 'yaadsaathi-2007.firebasestorage.app',
    measurementId: 'G-6NL4D3EF2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mfCjEQ4TsUXtZ1wvZiMnUQPx4xnfLWI',
    appId: '1:474736990075:android:0d65311549045730758fde',
    messagingSenderId: '474736990075',
    projectId: 'yaadsaathi-2007',
    storageBucket: 'yaadsaathi-2007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmyZ7r-fOojaNG42D8SaEHbJt_0lbuAgQ',
    appId: '1:474736990075:ios:4303ae3df935d07e758fde',
    messagingSenderId: '474736990075',
    projectId: 'yaadsaathi-2007',
    storageBucket: 'yaadsaathi-2007.firebasestorage.app',
    iosBundleId: 'com.example.yaadsaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmyZ7r-fOojaNG42D8SaEHbJt_0lbuAgQ',
    appId: '1:474736990075:ios:4303ae3df935d07e758fde',
    messagingSenderId: '474736990075',
    projectId: 'yaadsaathi-2007',
    storageBucket: 'yaadsaathi-2007.firebasestorage.app',
    iosBundleId: 'com.example.yaadsaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_G8q7MsBTAdA0TISIdvFQTfVOi5HjRk',
    appId: '1:474736990075:web:1cbd4c89efbbcd58758fde',
    messagingSenderId: '474736990075',
    projectId: 'yaadsaathi-2007',
    authDomain: 'yaadsaathi-2007.firebaseapp.com',
    storageBucket: 'yaadsaathi-2007.firebasestorage.app',
    measurementId: 'G-PL7CTKQRZP',
  );
}
